#!/usr/bin/perl

use strict;
use warnings;
use autodie qw(:all);
use Data::Dumper;
$Data::Dumper::Terse=1;
$\=$/="\n";
open(STDOUT,">arc/pkgs.pl");
sub slurp($){
  local @ARGV = @_;
  return grep { chomp || 1 } <ARGV>;
}
mkdir("arc/orig") unless -d "arc/orig";

our(%pkgs,$pkg,%pkg);

{
  my %md5 = map { reverse(split) } slurp("arc/md5sums");
  sub makePackage {
    local(%pkg);
    my $url = $_;
    #s{(tcl|expect|tzdata)(\d)}{$1-$2};

    my $re = qr{(.*)/((.*?)(-?)([0-9].*)(\.tar)(\.bz2|\.gz|\.xz))};
    my @parts = m{$re};
    @pkg{ qw( loc arc pkg dsh ver art cmp ) } = @parts;
    die unless grep { /^-?$/ } delete $pkg{dsh};
    $pkg{url}=$url;
    for($pkg{md5}){
      $_=delete $md5{$pkg{arc}};
      $_="" unless defined;
    };
    my $key=$pkg{pkg};
    my $val=\%pkg;
    $pkgs{$key}=$val;
  }
}
sub loadPackages() {
  my @urls = slurp("arc/wget-list");
  for(@urls) {
    if(s/\.patch$//){
    } else {
      makePackage();
    }
  };
};
loadPackages();
print Dumper(\%pkgs);
close(STDOUT);
