FROM ubuntu
WORKDIR /boot/strap/lfs
USER root
VOLUME [ "/tmp/tricky" ]

# COPY /boot/strap/lfs/apt-install.pl .
# RUN ln -sf bash /bin/sh
# RUN apt-get update  -y
# RUN apt-get upgrade -y
# RUN apt-get install -y git             rcs                  vim             vim-doc
# RUN apt-get install -y vim-scripts     bash-completion      g++             make
# RUN apt-get install -y gawk            python3              info            m4
# RUN apt-get install -y automake        autoconf             libtool         xz-utils
# RUN apt-get install -y bison           texinfo              links2          wget
# RUN apt-get install -y openssh-server  openssh-sftp-server  openssh-client  
# RUN apt-get install -y inetutils-ping  net-tools            flex            rsync

#source etc/env.sh
#bin/version_check.sh
#bin/create_base_dirs.sh
#bin/create_base_dirs.sh
#bin/create_lfs_user.sh
#bin/set_lfs_ownership.sh
#chown -R lfs.lfs ~lfs
#sudo -u lfs bash -c "source ~/etc/env.sh; cd; bash bin/populate_lfs_home.sh"
